/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7xNQDoK2TZy
 */
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export default function FirstPage() {
  return (
    <div className="bg-[#1a1a1a] text-white min-h-screen">
      <nav className="flex justify-between items-center py-4 px-8 border-b border-gray-700">
        <div className="text-xl font-bold">DeTask</div>
        <div className="flex space-x-4">
          <Button variant="ghost">EN|中文</Button>
          <Button variant="ghost">课题</Button>
        </div>
        <Button variant="secondary">Connect Wallet</Button>
      </nav>
      <div className="px-8 py-6">
        <div className="flex space-x-4 mb-6">
          <Button variant="default">TASK</Button>
          <Button variant="ghost">SMOVE</Button>
          <Button variant="ghost">GAME</Button>
          <Button variant="ghost">IDO</Button>
        </div>
        <div className="grid gap-4">
          <Card className="bg-gray-800">
            <CardContent>
              <div className="p-4">任务</div>
            </CardContent>
          </Card>
          <Card className="bg-gray-800">
            <CardContent>
              <div className="p-4">任务</div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
