/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vhdCQx1B6eo
 */
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function mainpage() {
  return (
    <div className="bg-[#1a1a1a] min-h-screen text-white">
      <nav className="flex justify-between items-center py-4 px-8 border-b border-gray-700">
        <div className="flex items-center space-x-4">
          <h1 className="text-xl font-bold">DeTask</h1>
          <div className="space-x-2">
            <Button className="bg-blue-600 hover:bg-blue-700 text-white">EN|中文</Button>
            <Button className="bg-transparent hover:bg-blue-700 text-white">课题</Button>
          </div>
        </div>
        <Button className="bg-transparent hover:bg-blue-700 text-white">Connect Wallet</Button>
      </nav>
      <div className="px-8 py-6">
        <div className="flex space-x-4 mb-6">
          <Button className="bg-blue-500 hover:bg-blue-600 text-white">TASK</Button>
          <Button className="bg-transparent hover:bg-blue-700 text-white">SMOVE</Button>
          <Button className="bg-transparent hover:bg-blue-700 text-white">GAME</Button>
          <Button className="bg-transparent hover:bg-blue-700 text-white">IDO</Button>
        </div>
        <div className="grid grid-cols-1 gap-4">
          <Card className="bg-gray-800 border border-gray-200 border-gray-600 dark:border-gray-800">
            <CardContent>
              <h2 className="text-lg font-semibold">任务</h2>
            </CardContent>
          </Card>
          <Card className="bg-gray-800 border border-gray-200 border-gray-600 dark:border-gray-800">
            <CardContent>
              <h2 className="text-lg font-semibold">任务</h2>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
